name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fickle-bean-reader-api" #Must be unique in Heroku
          heroku_email: "hicks2evan@gmail.com"
          appdir: "server"
          procfile: "web: npm start"
